services:
  tests:
    build: .
    environment:
      - BASE_URI=${BASE_URI:-}
    volumes:
      - ./build:/app/build

  report:
    image: frankescobar/allure-docker-service:latest
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
    ports:
      - "5050:5050"
    volumes:
      - ./build/allure-results:/app/allure-results
